variables:
    GIT_SSL_NO_VERIFY: "1"
    BUILD_DIR: build_x64_VS2019

build:
    tags:
        - build
        - finminer
        - office
        - win64
        - agent2

    script:
        - set BUILD_DIR=build_x64_VS2019
        - rmdir /S /Q %BUILD_DIR%
        - mkdir %BUILD_DIR%
        - cd %BUILD_DIR%
        - cmake ../ -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019"
        - cmake --build . --config=Release -j
        - cd ..


    artifacts:
        name: register-optimizer
        paths:
            - register-optimizer